{'id': 1033560, 'title_fa': 'کاتلا کاله - 200 گرم', 'title_en': 'Kaleh Katela - 200 gr',
 'url': {'base': None, 'uri': '/product/dkp-1033560/کاتلا-کاله-200-گرم'}, 'status': 'marketable',
 'has_quick_view': True, 'digiplus': {'services': ['ارسال رایگان'], 'is_jet_eligible': False, 'cash_back': 0,
                                      'is_general_location_jet_eligible': False},
 'data_layer': {'brand': 'کاله', 'category': '[DF,صبحانه]', 'metric6': 3530, 'dimension2': 0, 'dimension6': 0,
                'dimension7': 'none', 'dimension9': 4.1, 'dimension11': 1, 'dimension20': 'marketable'}, 'images': {
    'main': {'storage_ids': [], 'url': [
        'https://dkstatics-public.digikala.com/digikala-products/4877434.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80'],
             'thumbnail_url': None, 'temporary_id': None}}, 'rating': {'rate': 82, 'count': 3530},
 'default_variant': {'id': 2178182, 'lead_time': 0, 'rank': 8.87, 'rate': 86.6,
                     'statistics': {'totally_satisfied': {'rate_count': 1184, 'rate': 47.82},
                                    'satisfied': {'rate_count': 1008, 'rate': 40.71},
                                    'neutral': {'rate_count': 223, 'rate': 9.01},
                                    'dissatisfied': {'rate_count': 41, 'rate': 1.66},
                                    'totally_dissatisfied': {'rate_count': 20, 'rate': 0.81}, 'total_count': 2476,
                                    'total_rate': 86.6}, 'status': 'marketable',
                     'properties': {'is_fast_shipping': True, 'is_ship_by_seller': False, 'is_multi_warehouse': True,
                                    'has_similar_variants': False, 'is_rural': False, 'in_digikala_warehouse': True},
                     'digiplus': {'services': ['ارسال رایگان'], 'is_jet_eligible': False, 'cash_back': 0,
                                  'is_general_location_jet_eligible': False},
                     'warranty': {'id': 272, 'title_fa': 'گارانتی اصالت و سلامت فیزیکی کالا',
                                  'title_en': 'گارانتی اصالت و سلامت فیزیکی کالا'},
                     'seller': {'id': 1, 'title': 'دیجی\u200cکالا', 'code': '5A52N',
                                'url': 'https://www.digikala.com/seller/5A52N/',
                                'rating': {'total_rate': 0, 'total_count': 0, 'commitment': 100, 'no_return': 99.9,
                                           'on_time_shipping': 100},
                                'properties': {'is_trusted': False, 'is_official': False, 'is_roosta': False,
                                               'is_new': False}, 'stars': 5, 'registration_date': '6 سال و 1 هفته'},
                     'digiclub': {'point': 4},
                     'price': {'selling_price': 360000, 'rrp_price': 360000, 'order_limit': 10, 'is_incredible': False,
                               'is_promotion': False, 'is_locked_for_digiplus': False, 'discount_percent': 0},
                     'has_importer_price': False, 'manufacture_price_not_exist': False, 'manufacture_price': 284440,
                     'shipment_methods': {'description': 'موجود در انبار دیجی\u200cکالا', 'has_lead_time': True,
                                          'providers': [{'title': 'ارسال دیجی\u200cکالا',
                                                         'description': 'این کالا در انبار دیجی\u200cکالا موجود و آماده پردازش است و توسط پیک دیجی\u200cکالا در بازه انتخابی ارسال خواهد شد.',
                                                         'has_lead_time': False, 'type': 'digikala'},
                                                        {'title': 'ارسال سریع سوپرمارکتی دیجی\u200cکالا',
                                                         'description': 'این کالا در انبار دیجی\u200cکالا موجود و آماده پردازش است و توسط پیک دیجی\u200cکالا در بازه انتخابی ارسال خواهد شد.',
                                                         'has_lead_time': False, 'type': 'fresh'}]}},
 'properties': {'is_fast_shipping': True, 'is_ship_by_seller': False, 'is_multi_warehouse': True, 'is_fake': False,
                'has_gift': False, 'min_price_in_last_month': 299000, 'is_non_inventory': False, 'is_ad': False,
                'is_jet_eligible': False, 'is_medical_supplement': False}, 'badges': [], 'colors': []}
